package com.codevalley.app.utils

object Constants {
    const val BASE_URL = "https://api.example.com/"
    const val BEARER_TOKEN = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiZW1haWwiOiJyaWNhcmRvLmp1ZXpAZ21haWwuY29tIiwidXNlcm5hbWUiOiJjYXJsaXRvMDYwNSIsImxhc3RMb2dpbkF0IjoiMjAyNC0wNS0yOVQxODo0NDo0OC44NTBaIiwiY3JlYXRlZEF0IjoiMjAyNC0wNS0yOVQxODo0NDozOC45ODRaIiwiaXNUd29GYWN0b3JBdXRoZW50aWNhdGVkIjpmYWxzZSwiaWF0IjoxNzE3MDk0MzAzLCJleHAiOjE3MTcxODA3MDN9.m1eVUMlRTkxSAwR9vRfLReBG8znzjwGA2IXPTd7Kn9U"
}
